### ISSUE TITLE
Secret key in repository

### ISSUE THREAD

**Issue by just-paja** [just-paja/improtresk-api#1]
It is insecure to keep secret key in git repository despite it is just a development key. We need to find a way to hide this piece of configuration from repository and read production configuration.

**Comment by PetrDlouhy** [comment]
We usually solve this problem by including `settings_local.py` with local configuration from `settings.py` file.

**Comment by PetrDlouhy** [comment]
This code is placed at end of `settings.py`:
```
# import local settings
try:
    from settings_local import *  # noqa
except ImportError:
    pass
```

**Comment by just-paja** [comment]
I propose reading the secret key from environment variable. There is no need to pull in extra files that are not in the repository.

**Comment by PetrDlouhy** [comment]
Local settings are used for bunch of other stuff, that I would not place to the repository. Settings like admin mail, database, allowed hosts, email backend configuration.

**Comment by just-paja** [comment]
@PetrDlouhy, you can store the development values on local environment any way you want, but we need the application to read these from the environment.
