### ISSUE TITLE
Add payment status endpoint

### ISSUE THREAD

**Issue by just-paja** [just-paja/improtresk-api#128]
User needs to query often for status payment when he gets back from the payment gateway until it has been marked as one of the end status (Paid or Canceled). Create endpoint that contacts 

1. Checks the payment status and if the status is not Paid or Canceled, contacts GoPay API
2. Saves status to database if it has changed
3. Assigns people to workshop if the associated order is paid
4. Returns status and method of the payment

**Comment by PetrDlouhy** [comment]
This was partially implemented for account transfer payments. For GoPay enhancements follow to issue #157.
