### ISSUE TITLE
Create artifact for continuous delivery

### ISSUE THREAD

**Issue by just-paja** [just-paja/improtresk-api#13]
As server admin I need to receive a single file containing both code ready to run and all static files and dependencies to deploy the application on staging and production server as fast as possible.

**Comment by just-paja** [comment]
We've discussed this and output of the circle build will be a pip package. Server will then take the pip package, unpack it and install all dependencies around it.

**Comment by just-paja** [comment]
@PetrDlouhy, please add the pip packaging into circle.yml.

**Comment by PetrDlouhy** [comment]
@just-paja: This is already implemented, right?

**Comment by just-paja** [comment]
@PetrDlouhy, almost. Need to adjust configuration on server a little and it should be good to go.

**Comment by just-paja** [comment]
Set up continuous delivery of development releases to `api.staging.improtresk.cz`.
