### ISSUE TITLE
Some fields should not be required

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#17]
Fields are required (`blank=False`, `null=False`) by default in Django. Some fields like `Signup.birthday` or `Order.food` should probably not be required.

**Comment by just-paja** [comment]
Why? 

From the accounting perspective, we really need to know the participants birthday (to confirm his identity later) and his choice on food (to calculate the price).

**Comment by just-paja** [comment]
We've discussed this and we need to set capacities and image captions as not required.

We need to ask accounting people if we require users home address for signups.

**Comment by just-paja** [comment]
@PetrDlouhy, Home address is required field only for people who choose hotel as accomodation, but not necessary to collect it from people who choose otherwise.
