### ISSUE TITLE
Consider separating in few apps

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#20]
More Djangonautic approach is to separate project into more simple reusable apps. I would consider following apps: workshops, accomodation/food, signups, (transportation)

**Comment by just-paja** [comment]
@PetrDlouhy, I don't quite understand how this works. We shouldn't really be wasting time with making the application as nifty as possible. There is only one important question. What value would this bring to users?

**Comment by just-paja** [comment]
We've discussed this and we don't want to spend time deciding on how to separate the application, but we may separate it later if it comes to it.
