### ISSUE TITLE
Workshop reservation models

### ISSUE THREAD

**Issue by just-paja** [just-paja/improtresk-api#28]
As a participant, I need to be able to reserve spot on workshop for current year to be given some time to pay it. Create following models and relations:

* `Order`
  * `price`, number
  * `paid`, bool
  * `canceled`, bool
* `Payment` 
  * `type`, enum (card payment, account transfer, cash)
  * belongs to Order
* `Reservation`
  * `endsAt`, a date when the reservation becomes invalid
  * belongs to `Participant`, `WorkshopPrice`, `ReservationFoodTime`, `Order`
* `ReservationFoodTime`
  * belongs to `Reservation` and `FoodTime`
  * has many (n:m) `Food`
* `FoodTime`
  * has many `Food`s and `ReservationFoodTime`s
* `Food`
  * `name`, string
  * `course`, enum(soup, main)
  * belongs to `FoodTime`

**Comment by PetrDlouhy** [comment]
I am renaming FoodTime to Meal since it is more natural name.

**Comment by PetrDlouhy** [comment]
I am closing this and making new issue for the Payment model changes
