### ISSUE TITLE
Read only fields in Order

### ISSUE THREAD

**Issue by just-paja** [just-paja/improtresk-api#29]
Make price, participant and reservation read only in django Orders admin.

**Comment by PetrDlouhy** [comment]
Do you mean, that all fields on `Order` should be read-only? So that no order could be created by admin?

**Comment by PetrDlouhy** [comment]
I made `symvar`, `price` and `paid` fields read-only in PR #66. I had to make `Order.price` nullable though.

`reservation` is handled on the other side of relation and I think, that it is not needed to make read-only that one.
