### ISSUE TITLE
Payments model

### ISSUE THREAD

**Issue by just-paja** [just-paja/improtresk-api#30]
As administrator I need to see log from payment gateway. Save all status changes into CardPaymentLog model.

**Comment by PetrDlouhy** [comment]
I think, that this needs to be clarified a bit more before implementation. What fields will be stored in `CardPaymentLog`? Will we divide `Payment` model to simple payment and bank transfer, or will we user it for all three payment methods?

**Comment by just-paja** [comment]
Not sure at the moment. We should be logging [every aspect](https://doc.gopay.com/cs/#standardní-platba) of the payment that can help admins identify and pair the payment.

**Comment by PetrDlouhy** [comment]
OK, so I would leave this at current state until those things get cleared up.

**Comment by PetrDlouhy** [comment]
This was edited in PR #154 and other commits. Closing, feel free to open new issues with specific list of fields like #155.
