### ISSUE TITLE
Associate Accomodation to the Reservation model

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#62]
As a participant I need to be able to reserve accomodation.

**Comment by PetrDlouhy** [comment]
@just-paja The question is, if the relation between `Reservation` and `Accomodation` is `1:n` or `n:n`. In other works if a participant books only one accomodation place for whole festival or if we allow to book different accomodation for every day.

**Comment by just-paja** [comment]
@PetrDlouhy, good question. We definitely want him to be on one place only.

**Comment by PetrDlouhy** [comment]
This is resolved already.
