### ISSUE TITLE
Clarify Order-workshop relationship

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#8]
We need to decide whether we need to leave users with first, second and third workshop choice or we are able to secure that the workshop the user chooses first is reserved for him.

In first case, there should be through model (https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.ManyToManyField.through) for `workshops` parameter of `Signup` holding the order.

In second case, there would simply be `workshop` foreign key for `Signup`, but we need to ensure, that the signup is limited in time.

**Comment by just-paja** [comment]
We definitely need to keep both Signup and Order and relate both of them to the workshop. Consider these three different views of our users:

# As admin
I need to see a list of signups and be able to assign them to workshops regardless of what user ordered.
I need to see how many participants are *assigned* (signup) to each workshop to be able to assess status of workshop capacity.
I need to see how many future participants are *requesting* (order) to be assigned to each workshop to be able to assess status of workshop capacity and provide technical support for participants.

# As accountant
I need to review orders to know exactly what participants ordered and to be able to archive these records and use them for accounting purposes. 
I expect orders to be immutable with the exception of payment and payment status to be able to return taxes from what participants paid for.

# As participant
I want to be able to send payment by card transaction, so I don't need to reserve spot on multiple workshops.
I want to be able to send payment by account money transfer, so I need to reserve spot on multiple workshops.

**Comment by PetrDlouhy** [comment]
OK, then we need to use through model to hold sequence number of the workshops in order. Something like this: https://github.com/PetrDlouhy/improtresk-api/commit/463e417b9c92c5783aa66f0d52122be06b9e77f0

**Comment by just-paja** [comment]
Nice, that's exactly it, just the OrderToWorkshop is missing there.

**Comment by just-paja** [comment]
Discussed and separated this into #27 and #28.
