### ISSUE TITLE
Add verbose_name for Participant.rules field

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#84]

**Comment by PetrDlouhy** [comment]
@just-paja I wanted to add this, but I forgot the meaning of the `Participant.rules` field. I am unable to think up purpose of this field. What is the meaning of this?

**Comment by just-paja** [comment]
@PetrDlouhy, this field should carry the information that user willingly accepted rules of the festival. We can rename it so it's more obvious.
