### ISSUE TITLE
Create endpoint for texts

### ISSUE THREAD

**Issue by just-paja** [just-paja/improtresk-api#99]
We need readonly API that would return text detail.

**Comment by just-paja** [comment]
@PetrDlouhy, I would do it, but I'm not sure how to connect the `api` and `api_textual` and what is the purpose of the model separation.

**Comment by PetrDlouhy** [comment]
@just-paja The reason of the separation to `api` and `api_textual` Django applications is part of Django philosophy. Every aplication shoult  “Do one thing and do it well.” Every application should so simple, that it's purpose can be described by one sentence.
More on this in [Django documentation](https://docs.djangoproject.com/en/1.10/ref/applications/), [Reusable  apps documentation](http://django-reusable-app-docs.readthedocs.io/en/latest/) and Chapter 4.1 of [Two scoops of Django](https://www.pdf-archive.com/2016/08/07/two-scoops-of-django-1-8/).

How to connect them? Just make second include to the `urls`. I have made this in PR #100, with the difference, that I created separate `urls` module for `api_textual`.
